---
  - name: Docker-Install
    hosts: webservers
    become: true
    tasks:

    - name: Install docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install Python
      apt:
        name: python3-pip
        state: present

    - name: Install Docker PIP
      pip:
        name: docker
        state: present

    - name: Container Install
      docker_container:
        name: dvwa
        state: started
        image: cyberxsecurity/dvwa
        published_ports: 80:80
        state: started

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes